config/routes.rb
BlackstarRentApp::Application.routes.draw do

  root :to => 'sessions#new'

  namespace :admin do
    root :to => 'products#index'
    resources :users

    resources :product_stocks do
      resources :stock_histories, :only => [:index]
    end

    resources :products do
      get 'order'
      resources :ordered_products, :only => [:new, :create]
      resources :product_stocks, :only => [:new, :create, :show, :index]
      resources :orders, :only => [] do
        resources :ordered_products, :only => [:new]
      end
    end

    resources :ordered_products do
      member do
        put :set_sub_total
      end
    end

    resources :orders do
      get 'edit_detail'
      collection do
        get 'payments'
        get 'books'
        get 'build'
      end

      get 'print_original'
      get 'print'
      get 'print_deliver'
      resources :payments, :only => [:index, :new]
      resources :rented_products, :only => [:index]
    end

    resources :returned_products, :only => [:create]

    resources :payments, :only => [:create, :edit, :update, :destroy]
    
    resources :product do
      resources :product_packages, :only => [:new, :destroy]
    end
    
    resources :product_packages, :only => [:create]

  end

  resources :users
  resources :sessions

end

app/models/ordered_product.rb
class OrderedProduct < ActiveRecord::Base
  #  before_destroy do |ordered_product|
  #    product = ordered_product.product
  #    product.update_attribute(:stock, product.stock + ordered_product.qty)
  #  end
  
  belongs_to :order
  belongs_to :product
  has_many :rented_products, :dependent => :destroy

  attr_accessor :flash_error
  #  def save_or_update(ordered_product)
  #    unless self.id.blank? # untuk update data
  #      self.update_attributes(ordered_product)
  #    else  # untuk data baru
  #      self.save
  #    end
  #  end

#  def triggered_destroy
#    product = self.product
#    unless product.is_dimensional?
#      if product.is_package?
#        product.childs.each do |p|
#
#          total_reduced_stocks = p.reduced_stocks * self.qty
#          p.child.update_attribute(:stock, p.child.stock + total_reduced_stocks)
#
#          #        ProductStock.update_stocks(p.child.parents)
#        end
#      else
#        product.update_attribute(:stock, product.stock + self.qty)
#      end
#    end
#    self.destroy
#  end

  def self.get_new_ordered_products(user_id)
    self.where("user_id = ? AND order_id IS NULL", user_id)
  end

  def update_ordered_product(temp_ordered_product)
    self.update_attributes(temp_ordered_product)
    if self.order_id.blank?
      #      return "admin_products_path"
      return "/admin/orders/build"
    else
      order = self.order
      temp_order = {}
      temp_order[:total_price_per_day] = order.ordered_products.sum(:sub_total)
      temp_order[:total_price] = temp_order[:total_price_per_day] * order.duration_in_days + order.delivery_cost
      order.update_attributes(temp_order)
      #      return "admin_order_edit_detail_path(#{self.order_id})"
      return "/admin/orders/#{self.order_id}/edit_detail"
    end
  end

  def complex_triggered_update(temp_ordered_product, rp)
    success = true
    product = self.product
    err_msg = []
    rented_products = []
    return_url = ""
    OrderedProduct.transaction do
      if product.is_package? # if package then of course take a loop as many products contained in it
        products = product.childs.joins("LEFT JOIN products p ON product_packages.child_id = p.id
                                         LEFT JOIN (SELECT product_id, rented_qty
                                                    FROM rented_products
                                                    WHERE ordered_product_id = #{self.id}) rp ON product_packages.child_id = rp.product_id").
          select('product_packages.id, child_id, reduced_stocks, p.name, stock, rented_qty')
        products.each do |p|
          #          p "1 #{p.rented_qty}"
          if product.is_dimensional?
            if p.rented_qty.blank?
              total_reduced_stocks = p.reduced_stocks * rp["#{p.child_id}"]["rented_qty"].to_i
            else
              total_reduced_stocks = p.rented_qty - (p.reduced_stocks * rp["#{p.child_id}"]["rented_qty"].to_i)
            end
          else
            total_reduced_stocks = p.reduced_stocks * (self.qty - temp_ordered_product[:qty].to_i)
          end
          unless (product.is_dimensional? and total_reduced_stocks == 0)
#            if p.stock < -(total_reduced_stocks) # apabila stok barang tidak mencukupi
#              success = false
#              err_msg << "Stok #{p.name} tidak mencukupi"
#            else
#              if success
                if p.rented_qty.blank?
#                  p.child.update_attribute(:stock, p.stock - total_reduced_stocks)
                  rented_products << { :product_id => p.child_id,
                    :order_id => self.order_id,
                    :rented_qty => total_reduced_stocks,
                    :ordered_product_id => self.id
                  }
                else
                  rented_product = RentedProduct.where("ordered_product_id = ? AND product_id = ?",self.id, p.child_id).first
                  rented_product.update_attribute(:rented_qty, rented_product.rented_qty - total_reduced_stocks)
#                  p.child.update_attribute(:stock, p.stock + total_reduced_stocks) # stok sekarang - total qty lama + total qty baru
                end
#              end
#            end
          end
        end

        if success
          RentedProduct.create(rented_products)
          if product.is_dimensional?
            temp_ordered_product[:sub_total] = self.rent_price * temp_ordered_product[:width].to_f * temp_ordered_product[:height].to_f
          else
            temp_ordered_product[:sub_total] = self.rent_price * temp_ordered_product[:qty].to_i
          end
          temp_ordered_product[:ori_sub_total] = temp_ordered_product[:sub_total]
          return_url = self.update_ordered_product(temp_ordered_product)
        else
          return_url = self.generate_error_msg(err_msg)
          raise ActiveRecord::Rollback
        end
      else
#        unless product.stock < temp_ordered_product[:qty].to_i
#          product.update_attribute(:stock, product.stock + (self.qty - temp_ordered_product[:qty].to_i))
          temp_ordered_product[:sub_total] = self.rent_price * temp_ordered_product[:qty].to_i
          temp_ordered_product[:ori_sub_total] = temp_ordered_product[:sub_total]
          return_url = self.update_ordered_product(temp_ordered_product)
          self.rented_products.first.update_attribute(:rented_qty, self.qty)
#        else
#          return_url = self.generate_error_msg(err_msg)
#          raise ActiveRecord::Rollback
#        end
      end
    end

    return return_url
  end

  def complex_triggered_save(user_id, rp)
    success = true
    product = self.product
    err_msg = []
    rented_products = []
    return_url = ""
    OrderedProduct.transaction do
      if product.is_package? # if package then of course take a loop as many products contained in it
        products = product.childs.joins('LEFT JOIN products p ON product_packages.child_id = p.id').
          select('product_packages.id, child_id, reduced_stocks, p.name, stock')
        products.each do |p|
          if product.is_dimensional?
            total_reduced_stocks = p.reduced_stocks * rp["#{p.child_id}"]["rented_qty"].to_i
          else
            total_reduced_stocks = p.reduced_stocks * self.qty # menghitung total qty barang yang akan berkurang
          end
          unless (product.is_dimensional? and total_reduced_stocks == 0)
              rented_products << { :product_id => p.child_id,
                :order_id => self.order_id,
                :rented_qty => total_reduced_stocks,
              }
          end
        end

        if success
          return_url = self.save_ordered_product(product, user_id)
          rented_products.each { |r| r[:ordered_product_id] = self.id }
          RentedProduct.create(rented_products)
        else
          return_url = self.generate_error_msg(err_msg)
          raise ActiveRecord::Rollback
        end
      else
          return_url = self.save_ordered_product(product, user_id)
          rented_product = RentedProduct.new({ :product_id => self.product_id,
              :ordered_product_id => self.id,
              :order_id => self.order_id,
              :rented_qty => self.qty
            })
          rented_product.save
      end
    end
    return return_url
  end
#  def complex_triggered_update(temp_ordered_product, rp)
#    success = true
#    product = self.product
#    err_msg = []
#    rented_products = []
#    return_url = ""
#    OrderedProduct.transaction do
#      if product.is_package? # if package then of course take a loop as many products contained in it
#        products = product.childs.joins("LEFT JOIN products p ON product_packages.child_id = p.id
#                                         LEFT JOIN (SELECT product_id, rented_qty
#                                                    FROM rented_products
#                                                    WHERE ordered_product_id = #{self.id}) rp ON product_packages.child_id = rp.product_id#").
#          select('product_packages.id, child_id, reduced_stocks, p.name, stock, rented_qty')
#        products.each do |p|
#          #          p "1 #{p.rented_qty}"
#          if product.is_dimensional?
#            if p.rented_qty.blank?
#              total_reduced_stocks = p.reduced_stocks * rp["#{p.child_id}"]["rented_qty"].to_i
#            else
#              total_reduced_stocks = p.rented_qty - (p.reduced_stocks * rp["#{p.child_id}"]["rented_qty"].to_i)
#            end
#          else
#            total_reduced_stocks = p.reduced_stocks * (self.qty - temp_ordered_product[:qty].to_i)
#          end
#          unless (product.is_dimensional? and total_reduced_stocks == 0)
#            if p.stock < -(total_reduced_stocks) # apabila stok barang tidak mencukupi
#              success = false
#              err_msg << "Stok #{p.name} tidak mencukupi"
#            else
#              if success
#                if p.rented_qty.blank?
#                  p.child.update_attribute(:stock, p.stock - total_reduced_stocks)
#                  rented_products << { :product_id => p.child_id,
#                    :order_id => self.order_id,
#                    :rented_qty => total_reduced_stocks,
#                    :ordered_product_id => self.id
#                  }
#                else
#                  rented_product = RentedProduct.where("ordered_product_id = ? AND product_id = ?",self.id, p.child_id).first
#                  rented_product.update_attribute(:rented_qty, rented_product.rented_qty - total_reduced_stocks)
#                  p.child.update_attribute(:stock, p.stock + total_reduced_stocks) # stok sekarang - total qty lama + total qty baru
#                end
#              end
#            end
#          end
#        end
#
#        if success
#          RentedProduct.create(rented_products)
#          if product.is_dimensional?

app/controllers/admin/ordered_products_controller.rb
class Admin::OrderedProductsController < ApplicationController
  before_filter :admin_required
  after_filter :flash_error

  def flash_error
    if !@ordered_product.flash_error.blank?
      flash[:error] = @ordered_product.flash_error
    end
  end

  # GET /ordered_products
  # GET /ordered_products.json
  def index
    @ordered_products = OrderedProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ordered_products }
    end
  end

  # GET /ordered_products/1
  # GET /ordered_products/1.json
  def show
    @ordered_product = OrderedProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ordered_product }
    end
  end

  # GET /ordered_products/new
  # GET /ordered_products/new.json
  def new
    @product = Product.find(params[:product_id])
    @ordered_product = OrderedProduct.new(:product_id => params[:product_id], :order_id => params[:order_id],
      :qty => 1)
    if @product.is_dimensional? and @product.is_package?
#      @product_packages = @product.direct_childs
      @rented_products = RentedProduct.find_by_sql("SELECT product_id as id, name, NULL as rented_qty
                                                    FROM
                                                      (SELECT child_id as product_id
                                                       FROM product_packages
                                                       WHERE parent_id = #{params[:product_id]}) childs
                                                    LEFT JOIN products p ON childs.product_id = p.id")
    end
    render layout: false
  end

  # GET /ordered_products/1/edit
  def edit
    @ordered_product = OrderedProduct.find(params[:id])
    @product = @ordered_product.product
    if @product.is_dimensional? and @product.is_package?
      #      @product_packages = @product.direct_childs.joins("LEFT JOIN (SELECT product_id, rented_qty
      # FROM rented_products
      # WHERE ordered_product_id = 34) rp ON product_packages.child_id = rp.product_id#")
      #      .select("product_packages.id, name, rented_qty as qty")
      @rented_products = RentedProduct.find_by_sql("SELECT p.id, p.name, rented_qty
                                                    FROM
                                                      (SELECT child_id as product_id
                                                       FROM product_packages
                                                       WHERE parent_id = #{@product.id}) childs
                                                      LEFT JOIN (SELECT product_id, rented_qty
                                                                 FROM rented_products
                                                                 WHERE ordered_product_id = #{@ordered_product.id}) rp ON childs.product_id = rp.product_id
                                                      LEFT JOIN products p ON childs.product_id = p.id")
    end
    render layout: false
  end

  # POST /ordered_products
  # POST /ordered_products.json
  def create
    @ordered_product = OrderedProduct.new(params[:ordered_product])
    rented_products = params['rented_products'] ? params['rented_products'] : {}
    #    p product_packages
    respond_to do |format|
      format.html { redirect_to @ordered_product.complex_triggered_save(current_user.id, rented_products) }
    end
  end


  # PUT /ordered_products/1
  # PUT /ordered_products/1.json
  def update
    @ordered_product = OrderedProduct.find(params[:id])
    rented_products = params['rented_products'] ? params['rented_products'] : {}

    respond_to do |format|
      format.html { redirect_to @ordered_product.complex_triggered_update(params[:ordered_product], rented_products)}
    end
  end

  def set_sub_total
    new_sub_total = normal_format((params["fixnum"] || {})["to_s"])
    @ordered_product = OrderedProduct.find(params[:id])
    if @ordered_product.update_attribute(:sub_total, new_sub_total)
      head :ok
    end
  end

  # DELETE /ordered_products/1
  # DELETE /ordered_products/1.json
  def destroy
    @ordered_product = OrderedProduct.find(params[:id])
    product = @ordered_product.product
    order_id = @ordered_product.order_id

    @ordered_product.destroy

    respond_to do |format|
      if order_id.blank?
        format.html { redirect_to build_admin_orders_path }
      else
        change_order_total
        format.html { redirect_to admin_order_edit_detail_path(order_id) }
      end
    end
  end

  def update_returned_products
    #    p params
  end

  private
#  def set_up_ordered_product_for_create
#    @ordered_product.user_id = current_user.id
#    @ordered_product.price = @ordered_product.product.price
#    @ordered_product.rent_price = @ordered_product.product.rent_price
#    @ordered_product.sub_total = @ordered_product.rent_price * @ordered_product.qty
#  end

  def change_order_total
    @order = @ordered_product.order
    order = {}
    order[:total_price_per_day] = @order.ordered_products.sum(:sub_total)
    order[:total_price] = order[:total_price_per_day] * @order.duration_in_days + @order.delivery_cost
    @order.update_attributes(order)
  end
end

app/helpers/ordered_products_helper.rb
module OrderedProductsHelper
end

app/views/admin/ordered_products/_form.html.erb
<%= form_for([:admin, @ordered_product]) do |f| %>
  <div class="main-content" style="width:600px">
    <div class="form">
      <%= render :partial => 'partials/error_messages', :locals => { :obj => @ordered_product } %>

      <%= f.label 'Barang' %>
      <div class="show">
        <%= @ordered_product.product.name %>
      </div><br/>

      <% if @product.is_dimensional? %>
        <%= f.label 'ukuran' %>
        <%= f.text_field :width, :size => 1 %> &nbsp;&nbsp;&times;
        <%= f.text_field :height, :size => 1 %><br />
      <% else %>
        <%= f.label 'banyaknya' %>
        <%= f.text_field :qty %><br />
      <% end %>
      <%= f.label 'keterangan' %>
      <%= f.text_area :description %><br />

      <%= f.hidden_field :product_id %>

      <%= f.hidden_field :order_id %>
    </div>
    
    <% if @product.is_package? and @product.is_dimensional? %>
      <div class="form">
        <% @rented_products.each do |rp| %>
          <label>jml <%= rp.name %></label>
          <%= text_field_tag "rented_products[#{rp.id}][rented_qty]", rp.rented_qty, :size => 6 %><br/>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="footer">
    <%= f.submit 'Simpan' %>
  </div>
<% end %>

app/views/admin/ordered_products/_list.html.erb
<div  class="table_list">
  <table width="100%">
    <caption>Order</caption>
    <thead>
    <th>Banyaknya</th>
    <th>Nama Barang</th>
    <th>Harga</th>
    <th>Jumlah Harga</th>
    <th>Setelah Diskon</th>
    <th>Keterangan</th>
    <% unless links == 'off' %>
      <th colspan="2"></th>
    <% end %>
    </thead>
    <% sum_sub_total = 0 %>
    <% sum_ori_sub_total = 0 %>
    <% ordered_products.each do |ordered_product| %>
      <% sum_sub_total += ordered_product.sub_total %>
      <% sum_ori_sub_total += ordered_product.ori_sub_total %>
      <tr class="<%= cycle('odd', '') %>">
        <% if ordered_product.product.is_dimensional? %>
          <td class="right"><%= "#{number_format(ordered_product.width * ordered_product.height)} " %> m&sup2; <%=  " (#{number_format(ordered_product.width)} "%> &times; <%=" #{number_format(ordered_product.height)})" %></td>
        <% else %>
          <td class="right"><%= number_format(ordered_product.qty) %></td>
        <% end %>
        <td><%= ordered_product.product.name %></td>
        <td class="right"><%= money_format(ordered_product.rent_price) %></td>
        <td class="right"><%= money_format(ordered_product.ori_sub_total) %></td>
        <td class="right">
          <% unless links == 'off' %>
            <%= best_in_place ordered_product.sub_total, :to_s,
              :type => :input,
              :display_with => :number_to_currency,
              :helper_options => {:unit => '', :delimiter => '.', :precision => 0},
              :html_attrs => { :size => 5, :style => 'text-align:right', :id => "bip_sub_total_#{ordered_product.id}", :class => "bip_sub_total" },
              :path => set_sub_total_admin_ordered_product_path(ordered_product.id) %>
          <% else %>
            <%= money_format(ordered_product.sub_total) %>
          <% end %>
        </td>
        <td><%= ordered_product.description %></td>
        <% unless links == 'off' %>
          <td class="iconed_text">
            <%= link_to iconed_text('edit','Ubah'), edit_admin_ordered_product_path(ordered_product), :rel => 'facebox' %>
            <%= link_to iconed_text('del','Hapus'), [:admin, ordered_product], confirm: 'Apakah anda yakin?', :method => :delete %>
          </td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <td style="text-align: right" colspan="3"><b>Jumlah</b></td>
      <td style="text-align: right"><b><%= money_format(sum_ori_sub_total) %></b></td>
      <td style="text-align: right"><b><%= money_format(sum_sub_total) %></b></td>
    </tr>
    <% unless @order.blank? %>
      <% unless @order.id.blank? %>
        <tr>
          <td style="text-align: right" colspan="3"><b>Ongkos Kirim</b></td>
          <td style="text-align: right" colspan="2"><b><%= money_format(@order.delivery_cost) %></b></td>
        </tr>
        <tr>
          <td style="text-align: right" colspan="3"><b>Total</b></td>
          <td style="text-align: right" colspan="2"><b><%= money_format(sum_sub_total * @order.duration_in_days + @order.delivery_cost) %></b></td>
        </tr>
        <tr>
          <td style="text-align: right" colspan="3"><b>Terbilang</b></td>
          <td style="text-align: right" colspan="2"><b><%= terbilang(sum_sub_total * @order.duration_in_days + @order.delivery_cost) %> rupiah</b></td>
        </tr>
      <% end %>
    <% end %>
    <% unless links == 'off' %>
      <tr>
        <td align="right"><b>Terbilang</b></td>
        <td colspan="6"><b><%= terbilang(sum_sub_total) + "rupiah" unless sum_sub_total == 0 %></b></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/ordered_products/edit.html.erb
<div class="panel">
  <div class="header">ubah pesanan</div>
  <%= render 'form' %>
</div>

app/views/admin/ordered_products/index.html.erb
<h1>Listing ordered_products</h1>

<table>
  <tr>
    <th>Order</th>
    <th>Product</th>
    <th>Description</th>
    <th>Sub total</th>
    <th>Qty</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ordered_products.each do |ordered_product| %>
  <tr>
    <td><%= ordered_product.order_id %></td>
    <td><%= ordered_product.product_id %></td>
    <td><%= ordered_product.description %></td>
    <td><%= ordered_product.sub_total %></td>
    <td><%= ordered_product.qty %></td>
    <td><%= link_to 'Show', ordered_product %></td>
    <td><%= link_to 'Edit', edit_ordered_product_path(ordered_product) %></td>
    <td><%= link_to 'Destroy', ordered_product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ordered product', new_ordered_product_path %>

app/views/admin/ordered_products/new.html.erb
<div class="panel">
  <div class="header">pesanan</div>
  <%= render 'form' %>
</div>

app/views/admin/ordered_products/xxx_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order:</b>
  <%= @ordered_product.order_id %>
</p>

<p>
  <b>Product:</b>
  <%= @ordered_product.product_id %>
</p>

<p>
  <b>Description:</b>
  <%= @ordered_product.description %>
</p>

<p>
  <b>Sub total:</b>
  <%= @ordered_product.sub_total %>
</p>

<p>
  <b>Qty:</b>
  <%= @ordered_product.qty %>
</p>


<%= link_to 'Edit', edit_ordered_product_path(@ordered_product) %> |
<%= link_to 'Back', ordered_products_path %>