config/routes.rb
BlackstarRentApp::Application.routes.draw do

  root :to => 'sessions#new'

  namespace :admin do
    root :to => 'products#index'
    resources :users

    resources :product_stocks do
      resources :stock_histories, :only => [:index]
    end

    resources :products do
      get 'order'
      resources :ordered_products, :only => [:new, :create]
      resources :product_stocks, :only => [:new, :create, :show, :index]
      resources :orders, :only => [] do
        resources :ordered_products, :only => [:new]
      end
    end

    resources :ordered_products do
      member do
        put :set_sub_total
      end
    end

    resources :orders do
      get 'edit_detail'
      collection do
        get 'payments'
        get 'books'
        get 'build'
      end

      get 'print_original'
      get 'print'
      get 'print_deliver'
      resources :payments, :only => [:index, :new]
      resources :rented_products, :only => [:index]
    end

    resources :returned_products, :only => [:create]

    resources :payments, :only => [:create, :edit, :update, :destroy]
    
    resources :product do
      resources :product_packages, :only => [:new, :destroy]
    end
    
    resources :product_packages, :only => [:create]

  end

  resources :users
  resources :sessions

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :ordered_products, :dependent => :destroy
  has_many :products, :through => :ordered_products
  has_many :payments, :dependent => :destroy
  has_many :rented_products


#  before_destroy do |record|
#    record.ordered_products.destroy_all # would triggered rented_products to be destroyed by ordered_product having dependent :destroy relation with rented_product
#    record.rented_products.destroy_all
#  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.joins('LEFT JOIN users ON orders.user_id = users.id').
      order("delivery_date DESC, usage_date DESC")
    if params[:delivery_date].blank? and params[:usage_date].blank?
      params[:delivery_date] = Time.now.strftime("%Y-%m-%d")
    end
    @orders = @orders.where("delivery_date = ?", params[:delivery_date]) unless params[:delivery_date].blank?
    @orders = @orders.where("usage_date = ?", params[:usage_date]) unless params[:usage_date].blank?
    @orders = @orders.page(params[:page]).per(10).order("created_at DESC")

    @order = Order.new(:delivery_date => params[:delivery_date], :usage_date => params[:usage_date])

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.joins('LEFT JOIN users ON orders.user_id = users.id').find(params[:id])
    @ordered_products = @order.ordered_products
    @payments = @order.payments.order('created_at ASC')
    @grand_total = @ordered_products.sum(:sub_total) * @order.duration_in_days + @order.delivery_cost
    @total_payment = @payments.sum(:amount)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new
    @ordered_products = OrderedProduct.get_new_ordered_products(current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    #    success = false
    params[:order][:delivery_cost] = normal_format(params[:order][:delivery_cost])
    params[:payment] = normal_format(params[:payment])
    @order = Order.new(params[:order])
    @order.user_id = current_user.id
    @order.total_price_per_day = get_total_price_per_day
    @order.total_price = @order.total_price_per_day * @order.duration_in_days + @order.delivery_cost
    @ordered_products = OrderedProduct.get_new_ordered_products(current_user.id)

    respond_to do |format|
      begin
        Order.transaction do
          @order.save
          @ordered_products.each do |op|
            op.rented_products.update_all("order_id = #{@order.id}")
          end
          @ordered_products.update_all("order_id = #{@order.id}")
          Payment.create(:amount => params[:payment], :order_id => @order.id) if @order.payment_status == "Down Payment"
        end
        format.html { redirect_to admin_order_path(@order), notice: 'Pesanan telah berhasil disimpan' }
      rescue ActiveRecord::RecordInvalid => invalid
        format.html { render action: "new" }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])
    params[:order][:total_price] = @order.total_price_per_day * params[:order][:duration_in_days] + params[:order][:delivery_cost]

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    rp = ReturnedProduct.joins("LEFT JOIN rented_products rp ON returned_products.rented_product_id = rp.id
                                LEFT JOIN orders o ON rp.order_id = o.id").
      where("rp.order_id = ?", params[:id])
    if rp.blank?
      if @order.destroy
        flash[:notice] = "Pesanan telah dihapus"
      else
        flash[:error] = "Pesanan tidak dapat dihapus"
      end
    else
      flash[:error] = "Pesanan telah berjalan dan tidak dapat dihapus"
    end

    respond_to do |format|
      format.html { redirect_to admin_orders_url }
      format.json { head :ok }
    end
  end

  def edit_detail
    @order = Order.find(params[:order_id])
    @ordered_products = @order.ordered_products
    #    @products = Product.where("is_rented = ?", 1).page(params[:page]).per(10).order("created_at DESC")
    @products = Product.stocks_at(params[:usage_date]).page(params[:page]).per(10)
    @product = Product.new
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  #  def return_of_products
  #    @order = Order.find(params[:order_id])
  #    @ordered_products = @order.ordered_products
  #  end

  def payments
    @orders = Order.where("payment_status != 'Lunas'").joins('LEFT JOIN users ON orders.user_id = users.id')
  end

  def print
    @order = Order.find(params[:order_id])
    @ordered_products = @order.ordered_products
    @payments = @order.payments

    #    respond_to do |format|
    #      format.html
    #    end
    render layout: 'print'
  end

  def print_deliver
    @order = Order.find(params[:order_id])
    @order.update_attribute(:is_delivered, true)
    @ordered_products = @order.ordered_products

    render layout: 'print'
  end

  def books
    @orders = Order.order("created_at DESC").page(params[:page]).per(10)
    @products = Product.select("id, name").order("name ASC").where("is_package = ?", 0)
  end

  def build
    params[:is_rented] = 'true' if params[:is_rented].blank?

    if params[:usage_date].blank?
      time = Time.new
      params[:usage_date] = time.strftime("%Y-%m-%d")
    end
    
    @usage_date = params[:usage_date]

    #    @products = Product.stocks_in(params[:rent_date]).where("name LIKE ? AND is_rented = ?", "%#{params[:name]}%", params[:is_rented] == 'true' ? 1 : 0)
    #    @products = @products.page(params[:page]).per(10).order("b.created_at DESC")
    #    @products = Product.where("name LIKE ? AND is_rented = ?", "%#{params[:name]}%", params[:is_rented] == 'true' ? 1 : 0)
    #    @products = @products.where("is_package = ?", params[:is_package] == 'true' ? 1 : 0) unless params[:is_package].blank?
    #    @products = @products.where("is_dimensional = ?", params[:is_dimensional] == 'true' ? 1 : 0) unless params[:is_dimensional].blank?
    #    @products = @products.page(params[:page]).per(10).order("created_at DESC")
    

    @products = Product.stocks_at(params[:usage_date]).page(params[:page]).per(10)

    if params[:order_id].blank?
      @ordered_products = OrderedProduct.where(:user_id => current_user.id, :order_id => nil)
      #      @order = Order.new(:usage_date => params[:usage_date])
    else
      @order = Order.find(params[:order_id])
      @ordered_products = @order.ordered_products
    end
    @product = Product.new(:name => params[:name], :is_rented => params[:is_rented],
      :is_package => params[:is_package], :is_dimensional => params[:is_dimensional])

    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def get_total_price_per_day
    OrderedProduct.where("user_id = ? AND order_id IS NULL", current_user.id).sum(:sub_total)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_print_order.html.erb
<div class="panel">
  <div class="header">
    Data Pemesanan
  </div>
  <div class="main-content">
    <div class="form">
      <table width="100%">
        <tr>
          <td>
            <label>Pemesan</label>
            <div class="show"><%= @order.customer %></div><br/>

            <label>Alamat</label>
            <div class="show"><%= @order.address %>&nbsp;</div><br/>

            <label>Telepon</label>
            <div class="show"><%= @order.phone %></div><br/>
          </td>
          <% unless deliver %>
          <td>
            <label>No.</label>
            <div class="show"><%= @order.id %></div><br/>

            <label>Tanggal Kirim</label>
            <div class="show"><%= date_format_id(@order.delivery_date) %></div><br/>

            <label>Tanggal Pakai</label>
            <div class="show"><%= date_format_id(@order.usage_date) %></div><br/>

            <label>Durasi (per hari)</label>
            <div class="show"><%= @order.duration_in_days %></div><br/>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/_print_ordered_products.html.erb
<div class="table_list">
  <table width="100%">
    <caption>Perincian Sewa</caption>
    <thead>
    <th>Banyaknya</th>
    <th>Nama Barang</th>
    <th>Harga</th>
    <th>Jumlah Harga</th>
    </thead>
    <% @ordered_products.each do |ordered_product| %>
      <tr class="<%= cycle('odd', '') %>">
        <% if ordered_product.product.is_dimensional? %>
          <td class="right"><%= "#{number_format(ordered_product.width * ordered_product.height)} " %> m&sup2; <%=  " (#{number_format(ordered_product.width)} "%> &times; <%=" #{number_format(ordered_product.height)})" %></td>
        <% else %>
          <td class="right"><%= ordered_product.qty %></td>
        <% end %>
        <td><%= ordered_product.product.name %></td>
        <td class="right"><%= money_format(ordered_product.rent_price) %></td>
        <% if ori %>
          <td class="right"><%= money_format(ordered_product.ori_sub_total) %></td>
        <% else %>
          <td class="right"><%= money_format(ordered_product.sub_total) %></td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <td class="right" colspan="3"><b>Jumlah Harga / Hari</b></td>
      <td class="right"><b><%= money_format(@order.total_price_per_day) %></b></td>
    </tr>
    <tr>
      <td class="right" colspan="3"><b>Ongkos Kirim</b></td>
      <td class="right"><b><%= money_format(@order.delivery_cost) %></b></td>
    </tr>
    <tr>
      <td class="right" colspan="3"><b>Jumlah Untuk <%= @order.duration_in_days %> Hari + Ongkos Kirim</b></td>
      <td class="right"><b><%= money_format(@order.total_price) %></b></td>
    </tr>
    <tr>
      <td class="right" colspan="3"><b>Pembayaran</b></td>
      <td class="right">
        <b>
          <% sum_amount = 0 %>
          <ul>
            <% @payments.each do |payment| %>
              <li><%= money_format(payment.amount) %></li>
              <% sum_amount += payment.amount %>
            <% end %>
          </ul>
        </b>
      </td>
    </tr>
    <tr>
      <td class="right" colspan="3"><b>Sisa</b></td>
      <td class="right"><b><%= money_format(@order.total_price - sum_amount) %></b></td>
    </tr>
    <tr>
      <td><b>Terbilang</b></td>
      <td colspan="5"><b><%= terbilang(@order.total_price - sum_amount) %> rupiah</b></td>
    </tr>
  </table>
</div>

app/views/admin/orders/_products_table_for_order.html.erb
<table width="100%">
  <caption>Barang</caption>
  <thead>
  <th>Nama Produk</th>
  <th>Deskripsi</th>
  <!--<th>Harga Beli</th>-->
  <th>Harga Sewa</th>
  <th>Stok</th>
  <th></th>
</thead>
<% @products.each do |product| %>
  <tr class="<%= cycle('odd', '') %>">
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <!--<td class="right">-->
        <%#= money_format(product.price) %>
    <!--</td>-->
    <td class="right"><%= money_format(product.rent_price) %></td>
    <td class="right">
      <% if product.is_package? %>
      <%= number_format(product.package_stock(@usage_date)) %>
      <% else %>
      <%= number_format(product.remain.to_f) unless product.is_dimensional? %>
      <% end %>
    </td>
    <% unless @order.blank? %>
      <td class="iconed_text"><%= link_to iconed_text('cart','Pesan'), new_admin_product_order_ordered_product_path(product.id, @order), :rel => "facebox", :onclick => "javascript:$.facebox({ajax: this.href});return false;" if (!@ordered_products.any? { |o| o.product_id == product.id } || product.is_dimensional?) && product.is_rented? %></td>
    <% else %>
      <td class="iconed_text"><%= link_to iconed_text('cart','Pesan'), new_admin_product_ordered_product_path(product.id), :rel => "facebox", :onclick => "javascript:$.facebox({ajax: this.href});return false;" if (!@ordered_products.any? { |o| o.product_id == product.id } || product.is_dimensional?) && product.is_rented? %></td>
    <% end %>
  </tr>
<% end %>
<tr>
  <td class="center" colspan="6"><%= paginate @products %></td>
</tr>
</table>

app/views/admin/orders/_search.html.erb
<div class="panel">
  <div class="header">
    Cari Order
  </div>

  <%= form_tag admin_orders_path, :method => :get, :remote => true do %>
    <%= render :partial => 'search_form' %>
  <% end %>
</div>

app/views/admin/orders/_search_form.html.erb
<div class="main-content">
  <div class="form">
      <%= text_field_tag :delivery_date, @order.delivery_date, :size => '5', :maxlength => '10', :placeholder => "tanggal kirim" %>
      <button id="btn_delivery_date">...</button>
      <script type="text/javascript">
        //<![CDATA[
        Calendar.setup({
          inputField : "delivery_date",
          trigger : "btn_delivery_date",
          onSelect : function() { this.hide() },
          dateFormat : "%Y-%m-%d"
        });
        //]]>
      </script>
      <%= text_field_tag :usage_date, @order.usage_date, :size => '5', :maxlength => '10', :placeholder => "tanggal pakai" %>
      <button id="btn_usage_date">...</button>
      <script type="text/javascript">
        //<![CDATA[
        Calendar.setup({
          inputField : "usage_date",
          trigger : "btn_usage_date",
          onSelect : function() { this.hide() },
          dateFormat : "%Y-%m-%d"
        });
        //]]>
      </script>
    <%#= text_field_tag :name, @product.name, :placeholder => 'nama barang' %>
    <%#= select_tag :is_rented, options_for_select({"Barang Sewa" => "true",
        "Barang Non Sewa" => "false"}, :selected => "#{@product.is_rented}") %>
    <%#= select_tag :is_package, options_for_select({"Dua-duanya" => "",
        "Paket" => "true",
        "Non Paket" => "false"}, :selected => "#{@product.is_package}") %>
    <%#= select_tag :is_dimensional, options_for_select({"Dua-duanya" => "",
        "Tenda" => "true",
        "Non Tenda" => "false"}, :selected => "#{@product.is_dimensional}") %>
    <%#= hidden_field_tag :order_id, @order.id unless @order.blank? %>
  </div>
</div>

<div class="footer">
  <%= submit_tag 'Cari', :id => 'search_button' %>
</div>

app/views/admin/orders/_show.html.erb
<div class="panel">
  <div class="header">
    Detail Order
  </div>
  <div class="main-content">
    <div class="form">
      <table width="100%">
        <tr>
          <td>
            <label>No Order</label>
            <div class="show"># <%= @order.id %></div><br/>

            <label>Pemesan</label>
            <div class="show"><%= @order.customer %></div><br/>

            <label>Alamat</label>
            <div class="show"><%= @order.address %>&nbsp;</div><br/>

            <label>Telepon</label>
            <div class="show"><%= @order.phone %></div><br/>
          </td>
          <td>
            <label>Tanggal Kirim</label>
            <div class="show"><%= @order.delivery_date %></div><br/>

            <label>Tanggal Pakai</label>
            <div class="show"><%= @order.usage_date %></div><br/>
            
            <label>Durasi (per hari)</label>
            <div class="show"><%= @order.duration_in_days %></div><br/>

            <label>Status</label>
            <div class="show"><%= @order.payment_status %></div><br/>

            <label>User</label>
            <div class="show"><%= @order.user.username %></div><br/>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/edit_detail.html.erb
<%= render :partial => 'admin/ordered_products/list', :locals => { :ordered_products => @ordered_products, :links => 'on' } %>
<br/>

<%= render :partial => 'admin/products/search' %>
<br/>

<div class="table_list" id="products_table">
  <%= render :partial => 'admin/products/products_table' %>
</div>

app/views/admin/orders/index.js.erb
$('#orders_table').html('<%= escape_javascript(render :partial => "orders_table") %>');
$.setAjaxPagination();

app/views/admin/orders/new.html.erb
<div class="panel">
  <div class="header">
    Order
  </div>
  <%= render 'form' %>
</div>

<%= hidden_field_tag :sum_sub_total, @ordered_products.sum(:sub_total) %>
<br />
<%= render :partial => 'admin/ordered_products/list', :locals => { :ordered_products => @ordered_products, :links => 'off' } %>

app/views/admin/orders/payments.html.erb
<div  class="table_list">
  <table width="100%">
    <caption>Order</caption>
    <thead>
    <th>Customer</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Delivery date</th>
    <th>Usage date</th>
    <th>Duration in days</th>
    <th>Total price per day</th>
    <th>Total price</th>
    <th>Payment status</th>
    <th>User</th>
    <th colspan="4"></th>
    </thead>

    <% @orders.each do |order| %>
      <tr class="<%= cycle('odd', '') %>">
        <td><%= order.customer %></td>
        <td><%= order.address %></td>
        <td><%= order.phone %></td>
        <td><%= order.delivery_date %></td>
        <td><%= order.usage_date %></td>
        <td class="right"><%= order.duration_in_days %></td>
        <td class="right"><%= money_format(order.total_price_per_day) %></td>
        <td class="right"><%= money_format(order.total_price) %></td>
        <td><%= order.payment_status %></td>
        <td><%= order.user.username %></td>
        <td><%= link_to 'Pembayaran', admin_order_payments_path(order) %></td>
        <td><%= link_to 'Tambah Pembayaran', new_admin_order_payment_path(order), :rel => 'facebox' %></td>
      </tr>
    <% end %>

  </table>
</div>

app/views/admin/orders/print.html.erb
<table width="100%">
  <tr>
    <td style="text-align: center">
      <%= image_tag("Logo.jpg", :size => '100x100') %><br/>
      <b>H A Y A T</b>
    </td>
    <td><%= render :partial => 'print_order', :locals => { :deliver => false } %></td>
  </tr>
  <tr>
    <td colspan="2">
      <%= render :partial => 'print_ordered_products', :locals => { :ori => false } %>
    </td>
  </tr>
  <tr>
    <td colspan="2"><br/></td>
  </tr>
  <tr>
    <td colspan="2">
      <table class="normal_text" width="100%">
        <tr>
          <td width="56%">
            CATATAN :
            <ol>
              <li>Hilang/Cacat/Rusak, diganti penuh oleh penyewa.</li>
              <li>Membatalkan/tidak diambil, uang muka hapus.</li>
              <li>Barang kembali dari tanggal yang telah ditentukan pembayaran diperhitungkan kembali.</li>
            </ol>
          </td>
          <td width="10%"></td>
          <td style="text-align: center">
            Bandung, <%= date_format_id(Time.now) %>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <b>HAYAT</b>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

app/views/admin/orders/print_deliver.html.erb
<table width="100%">
  <tr>
    <td style="text-align: center">
      <%= image_tag("Logo.jpg", :size => '100x100') %><br/>
      <b>H A Y A T</b>
    </td>
    <td>
      <%= render :partial => 'print_order', :locals => { :deliver => true } %>
    </td>
  </tr>
  <tr class="normal_text">
    <td colspan="2">
      <table width="100%">
        <tr>
          <td width="50%">MOHON DITERIMA & PERIKSA KEMBALI</td>
          <td width="50%" style="text-align: right">
            Bandung, <%= date_format_id(Time.now) %>&nbsp;&nbsp;&nbsp;&nbsp;
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td colspan="2">
      <div class="table_list">
        <table width="100%">
          <caption>Perincian Sewa</caption>
          <thead>
          <th>Nama Barang</th>
          <th>Banyaknya</th>
          <th>Keterangan</th>
          </thead>
          <% @ordered_products.each do |ordered_product| %>
            <tr class="<%= cycle('odd', '') %>">
              <td><%= ordered_product.product.name %></td>
              <% if ordered_product.product.is_dimensional? %>
                <td class="right"><%= "#{number_format(ordered_product.width * ordered_product.height)} " %> m&sup2; <%=  " (#{number_format(ordered_product.width)} "%> &times; <%=" #{number_format(ordered_product.height)})" %></td>
              <% else %>
                <td class="right"><%= ordered_product.qty %></td>
              <% end %>
              <td><%= money_format(ordered_product.description) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </td>
  </tr>
  <tr>
    <td colspan="2"><br/></td>
  </tr>
  <tr>
    <td colspan="2">
      <table class="normal_text" width="100%">
        <tr>
          <td width="30%" style="text-align: center; vertical-align: top">
            PENERIMA
          </td>
          <td width="40%"></td>
          <td style="text-align: center">
            HORMAT KAMI,
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <b>HAYAT</b>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

app/views/admin/orders/xxx_edit_detail.js.erb
$('#products_table').html('<%= escape_javascript(render :partial => "admin/products/products_table") %>');
$.setAjaxPagination();

app/views/admin/orders/xxx_search_products.html.erb
<div class="panel">
  <div class="header">
    Cari Barang
  </div>

  <%= form_tag admin_order_edit_detail_path(@order), :method => :get, :remote => true do %>
    <div class="main-content">
      <div class="form">
        <%= label_tag 'Nama Barang' %>
        <%= text_field_tag :name %>
      </div>
    </div>

    <div class="footer">
      <%= submit_tag 'Cari', :id => 'search_button' %>
    </div>
  <% end %>
</div>