config/routes.rb
BlackstarRentApp::Application.routes.draw do

  root :to => 'sessions#new'

  namespace :admin do
    root :to => 'products#index'
    resources :users

    resources :product_stocks do
      resources :stock_histories, :only => [:index]
    end

    resources :products do
      get 'order'
      resources :ordered_products, :only => [:new, :create]
      resources :product_stocks, :only => [:new, :create, :show, :index]
      resources :orders, :only => [] do
        resources :ordered_products, :only => [:new]
      end
    end

    resources :ordered_products do
      member do
        put :set_sub_total
      end
    end

    resources :orders do
      get 'edit_detail'
      collection do
        get 'payments'
        get 'books'
        get 'build'
      end

      get 'print_original'
      get 'print'
      get 'print_deliver'
      resources :payments, :only => [:index, :new]
      resources :rented_products, :only => [:index]
    end

    resources :returned_products, :only => [:create]

    resources :payments, :only => [:create, :edit, :update, :destroy]
    
    resources :product do
      resources :product_packages, :only => [:new, :destroy]
    end
    
    resources :product_packages, :only => [:create]

  end

  resources :users
  resources :sessions

end

app/models/product_stock.rb
class ProductStock < ActiveRecord::Base
  def update_stock_history(product_stock, description)
      stock_history = StockHistory.new(:old => self.stock,
                                       :new => product_stock[:stock],
                                       :product_stock_id => self.id,
                                       :description => description)
      stock_history.save
  end

  def triggered_save
    self.save
    product = self.product
    product.update_attribute(:stock, product.stock + self.stock)
#    update_stocks(product.parents)
  end

  def triggered_update_attributes(product_stock_array)
    old_stock = self.stock
    self.update_attributes(product_stock_array)
    gap = old_stock - self.stock
    product = self.product
    product.update_attribute(:stock, product.stock - gap)
#    update_stocks(product.parents)
  end

#  def self.update_stocks(parents)
#    parents.each do |parent|
#      min = ProductPackage.where(:parent_id => parent.parent_id).joins('LEFT JOIN products p ON product_packages.child_id = p.id').minimum('stock / product_packages.reduced_stocks')
#      parent.parent.update_attribute(:stock, min)
#    end
#  end

  belongs_to :product
  has_many :stock_histories
  has_many :rented_products

end

app/controllers/admin/product_stocks_controller.rb
class Admin::ProductStocksController < ApplicationController
  before_filter :admin_required
  #  layout nil, :only => :new
  
  # GET /product_stocks
  # GET /product_stocks.json
  def index
    @product = Product.find(params[:product_id])
    @product_stocks = @product.product_stocks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_stocks }
    end
  end

  # GET /product_stocks/1
  # GET /product_stocks/1.json
  def show
    @product_stock = ProductStock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_stock }
    end
  end

  # GET /product_stocks/new
  # GET /product_stocks/new.json
  def new
    @product_stock = ProductStock.new(:product_id => params[:product_id])
    render layout: false
  end

  # GET /product_stocks/1/edit
  def edit
    @product_stock = ProductStock.find(params[:id])
    render layout: false
  end

  # POST /product_stocks
  # POST /product_stocks.json
  def create
    @product_stock = ProductStock.new(params[:product_stock])

    respond_to do |format|
      if @product_stock.triggered_save
        format.html { redirect_to admin_product_product_stocks_path(@product_stock.product), notice: 'Product stock was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /product_stocks/1
  # PUT /product_stocks/1.json
  def update
    @product_stock = ProductStock.find(params[:id])

    respond_to do |format|
      ProductStock.transaction do
        if @product_stock.update_stock_history(params[:product_stock], params[:description]) &&
            @product_stock.triggered_update_attributes(params[:product_stock])
          format.html { redirect_to admin_product_product_stocks_path(@product_stock.product), notice: 'Product stock was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end
  end

  # DELETE /product_stocks/1
  # DELETE /product_stocks/1.json
  def destroy
    @product_stock = ProductStock.find(params[:id])
    @product_stock.destroy

    respond_to do |format|
      format.html { redirect_to product_stocks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/product_stocks_helper.rb
module ProductStocksHelper
end

app/views/admin/product_stocks/_form.html.erb
<%= form_for([:admin, @product_stock]) do |f| %>
  <div class="main-content" style="width:400px">
    <div class="form">
      <%= render :partial => 'partials/error_messages', :locals => { :obj => @product_stock } %>

      <%= f.label 'stok' %>
      <%= f.text_field :stock, :size => 5 %><br />

      <%= f.hidden_field :product_id %>

      <% unless @product_stock.id.blank? %>
        <%= f.label :deskripsi %>
        <%= text_area_tag :description %><br />
      <% end %>
    </div>
  </div>
  <div class="footer">
    <%= f.submit 'Simpan' %>
  </div>
<% end %>

app/views/admin/product_stocks/edit.html.erb
<div class="panel">
  <div class="header">
    Ubah Stok Barang
  </div>
  <%= render 'form' %>
</div>

app/views/admin/product_stocks/index.html.erb
<%= render :partial => 'admin/products/show', :locals => { :product => @product } %>

<br/>

<div class="link">
  <%= link_to 'Ubah', edit_admin_product_path(@product), :rel => "facebox" %>
  <%= link_to 'Kembali', admin_products_path %>
  <%= link_to 'Tambah stok', new_admin_product_product_stock_path(@product), :rel => 'facebox' %>
</div>

<br/>

<div class="table_list" style="width:50%">
  <table width="100%">
    <caption>Stok</caption>
    <thead>
    <th colspan="2"></th>
    <th>Stok</th>
    </thead>
    <% total_stock = 0 %>
    <% @product_stocks.each do |product_stock| %>
      <% total_stock += product_stock.stock %>
      <tr class="<%= cycle('odd', '') %>">
        <td><%= link_to 'Edit', edit_admin_product_stock_path(product_stock), :rel => 'facebox' %></td> <!-- stock_histories :index -->
        <td><%= link_to 'Histori Stok', admin_product_stock_stock_histories_path(product_stock), :rel => 'facebox' %></td> <!-- stock_histories :index -->
        <td class="right"><%= product_stock.stock %></td>
      </tr>
    <% end %>
      <tr>
        <td colspan="2" class="right"><strong>Total Stok Keseluruhan</strong></td>
        <td class="right"><%= total_stock %></td>
      </tr>
  </table>
</div>

app/views/admin/product_stocks/new.html.erb
<div class="panel">
  <div class="header">
    Tambah Stok Barang
  </div>
  <%= render 'form' %>
</div>

app/views/admin/product_stocks/xxx_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stock:</b>
  <%= @product_stock.stock %>
</p>

<p>
  <b>Product:</b>
  <%= @product_stock.product_id %>
</p>


<%= link_to 'Edit', edit_product_stock_path(@product_stock) %> |
<%= link_to 'Back', product_stocks_path %>