config/routes.rb
BlackstarRentApp::Application.routes.draw do

  root :to => 'sessions#new'

  namespace :admin do
    root :to => 'products#index'
    resources :users

    resources :product_stocks do
      resources :stock_histories, :only => [:index]
    end

    resources :products do
      get 'order'
      resources :ordered_products, :only => [:new, :create]
      resources :product_stocks, :only => [:new, :create, :show, :index]
      resources :orders, :only => [] do
        resources :ordered_products, :only => [:new]
      end
    end

    resources :ordered_products do
      member do
        put :set_sub_total
      end
    end

    resources :orders do
      get 'edit_detail'
      collection do
        get 'payments'
        get 'books'
        get 'build'
      end

      get 'print_original'
      get 'print'
      get 'print_deliver'
      resources :payments, :only => [:index, :new]
      resources :rented_products, :only => [:index]
    end

    resources :returned_products, :only => [:create]

    resources :payments, :only => [:create, :edit, :update, :destroy]
    
    resources :product do
      resources :product_packages, :only => [:new, :destroy]
    end
    
    resources :product_packages, :only => [:create]

  end

  resources :users
  resources :sessions

end

app/models/product.rb
class Product < ActiveRecord::Base
  #hm
  has_many :product_stocks
  has_many :rented_products

  # hmt
  has_many :orders, :through => :ordered_products
  has_many :ordered_products

  has_many :products, :through => :product_packages
  has_many :parents, :class_name => 'ProductPackage', :foreign_key => 'child_id'
  has_many :childs, :class_name => 'ProductPackage', :foreign_key => 'parent_id'

  after_save :update_stocks

  def update_stocks
    parents = self.parents
    parents.each do |parent|
      min = ProductPackage.where(:parent_id => parent.parent_id).
        joins('LEFT JOIN products p ON product_packages.child_id = p.id').
        minimum('stock / product_packages.reduced_stocks')
      parent.parent.update_attribute(:stock, min)
    end
  end
  #  after_save do |product|
  #    parents = product.parents
  #    parents.each do |parent|
  #      min = ProductPackage.where(:parent_id => 5).joins('LEFT JOIN products p ON product_packages.child_id = p.id').select(:stock).minimum(:stock)
  #      parent.parent.update_attribute(:stock, min)
  #    end
  #  end

  def triggered_save
    self.save
  end
  
  def triggered_update_attributes(product_array)
    self.update_attributes(product_array)
  end

  def triggered_destroy
    parents = self.parents
    parents.each do |parent|
      min = ProductPackage.where("parent_id = ? and child_id != ?", parent.parent_id, self.id).
        joins('LEFT JOIN products p ON product_packages.child_id = p.id').
        minimum('stock / product_packages.reduced_stocks')
      parent.parent.update_attribute(:stock, min)
      parent.destroy
    end

    self.destroy
  end

  def direct_childs
    childs.select("products.id, name, description, price, rent_price, stock, is_package, is_rented, stock_out, is_dimensional, reduced_stocks, parent_id").
      joins("LEFT JOIN products ON product_packages.child_id = products.id")

    #    where("parent_id = ?", product_id).
  end

  #  def self.stocks_in(date)
  #    find_by_sql("SELECT a.product_id as id, name, description, price, rent_price, is_package, is_rented, stock_out, is_dimensional, stock, rented_qty, (stock - rented_qty) as remain
  #                  FROM (SELECT product_id, name, description, price, rent_price, is_package, is_rented, stock_out, is_dimensional, SUM(a.stock) as stock
  #                        FROM product_stocks a
  #                             LEFT JOIN products b ON a.product_id = b.id
  #                        GROUP BY product_id) a
  #                       LEFT JOIN (SELECT product_id, SUM(rented_qty) as rented_qty
  #                            FROM rented_products a
  #                            LEFT JOIN orders b ON a.order_id = b.id
  #                            WHERE b.delivery_date = '#{date}'
  #                            GROUP BY product_id) b ON a.product_id = b.product_id#")
  #  end

  scope :stocks, joins("LEFT JOIN product_stocks b ON products.id = b.product_id").
    group("b.product_id").
    select("products.id as id, name, description, price, rent_price, is_package, is_rented, stock_out, is_dimensional, SUM(b.stock) as stock")
  scope :stocks_at, lambda { |date|
    stocks.joins("LEFT JOIN (SELECT product_id, SUM(rented_qty) as rented_qty
                             FROM rented_products a
                             LEFT JOIN orders b ON a.order_id = b.id
                             WHERE '#{date}' BETWEEN b.delivery_date AND DATE_ADD(b.usage_date, INTERVAL (b.duration_in_days - 1) DAY)
                             GROUP BY product_id) c ON b.product_id = c.product_id").
      select("COALESCE(rented_qty, 0) as rented_qty, (SUM(b.stock) - COALESCE(rented_qty, 0)) as remain")
  }
#  scope :stocks_at, lambda { |date|
#    stocks.joins("LEFT JOIN (SELECT product_id, SUM(rented_qty) as rented_qty
#                             FROM rented_products a
#                             LEFT JOIN orders b ON a.order_id = b.id
#                             WHERE b.delivery_date = '#{date}'
#                             GROUP BY product_id) c ON b.product_id = c.product_id#").
#      select("COALESCE(rented_qty, 0) as rented_qty, (SUM(b.stock) - COALESCE(rented_qty, 0)) as remain")
#  }

  def package_stock(date)
    product = Product.find_by_sql("SELECT MIN(remain) as remain
                           FROM
                           (SELECT SUM(stock) -  COALESCE(rented_qty, 0) as remain
                           FROM (SELECT child_id FROM product_packages WHERE parent_id = #{self.id}) a
                                      LEFT JOIN product_stocks b ON a.child_id = b.product_id
                                      LEFT JOIN  (SELECT product_id, SUM(rented_qty) as rented_qty
                                                         FROM rented_products a LEFT JOIN orders b ON a.order_id = b.id
                                                         WHERE '#{date}' BETWEEN b.delivery_date AND DATE_ADD(b.usage_date, INTERVAL (b.duration_in_days - 1) DAY)
                                                         GROUP BY product_id) c ON b.product_id = c.product_id
                           GROUP BY b.product_id) a")
    product.first.remain
  end

#  def available_for_package
#    Product.where("products.id = ? AND child_id IS NULL", self.id).
#            joins("LEFT JOIN (SELECT child_id
#                              FROM product_packages
#                              WHERE parent_id = #{self.id}) b ON products.id = b.child_id#")
#  end

  scope :available_for_package, lambda { |id|
    where("products.id != ? AND child_id IS NULL", id).
    joins("LEFT JOIN (SELECT child_id
                      FROM product_packages
                      WHERE parent_id = #{id}) b ON products.id = b.child_id")
  }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_filter :admin_required
  # GET /products
  # GET /products.json
  def index
    params[:is_rented] = 'true' if params[:is_rented].blank?
    @products = Product.where("name LIKE ? AND is_rented = ?", "%#{params[:name]}%", params[:is_rented] == 'true' ? 1 : 0)
    @products = @products.where("is_package = ?", params[:is_package] == 'true' ? 1 : 0) unless params[:is_package].blank?
    @products = @products.where("is_dimensional = ?", params[:is_dimensional] == 'true' ? 1 : 0) unless params[:is_dimensional].blank?
    @products = @products.page(params[:page]).per(10).order("created_at DESC")
    
    @product = Product.new(:name => params[:name], :is_rented => params[:is_rented],
      :is_package => params[:is_package], :is_dimensional => params[:is_dimensional])

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @product_packages = ProductPackage.where(:parent_id => params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @product.is_rented = true
    render layout: false
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    render layout: false
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.triggered_save
        format.html { redirect_to [:admin, @product], notice: "Product was successfully created. #{link_add_product}".html_safe }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.triggered_update_attributes(params[:product])
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: [:admin, @product.errors], status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.triggered_destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :ok }
    end
  end

  def order
    @ordered_product = OrderedProduct.new(:user_id => current_user.id,
      :product_id => params[:id],
      :qty => 1)
  end

  #  def save_order
  #    @product = Product.find(params[:id])
  #    @ordered_product = OrderedProduct.where(:user_id => current_user.id, :product_id => params[:id])
  #
  #    unless @ordered_product.blank?
  #      @ordered_product.update_attribute(:qty => @ordered_product.qty + 1,
  #                                        :sub_total => @product.rent_price * (@ordered_product.qty + 1))
  #    else
  #      @ordered_product = OrderedProduct.new(:user_id => current_user.id,
  #                                            :product_id => params[:id],
  #                                            :qty => 1,
  #                                            :sub_total => @product.rent_price)
  #    end
  #    @ordered_product.save
  #
  #    respond_to do |format|
  #      format.html { redirect_to admin_products_url }
  #      format.js
  #    end
  #  end
  private
  def link_add_product
    "<div class='link'>#{view_context.link_to('Tambah Barang', new_admin_product_path, :rel => 'facebox')}</div>"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <div class="main-content" style="width:600px">
    <div class="form">
      <%= render :partial => 'partials/error_messages', :locals => { :obj => @product } %>

      <%= f.label 'Nama Barang' %>
      <%= f.text_field :name %><br />

      <%= f.label 'Dapat disewa' %>
      <%= f.check_box :is_rented, :class => 'check-box' %>&nbsp;<br />

      <%= f.label 'Paket Barang' %>
      <%= f.check_box :is_package, :class => 'check-box' %>&nbsp;<br />

      <%= f.label 'Barang Berdimensi' %>
      <%= f.check_box :is_dimensional, :class => 'check-box' %>&nbsp;<br />

      <%= f.label 'Deskripsi' %>
      <%= f.text_area :description %><br />

      <%= f.label 'Harga Baru' %>
      <%= f.text_field :price %><br />

      <%= f.label 'Harga Sewa' %>
      <%= f.text_field :rent_price %><br />

      <%= f.label 'Stok' %>
      <div class="show"><%= @product.stock.to_i %></div><br />
    </div>
  </div>
  <div class="footer">
    <%= f.submit 'Simpan' %>
  </div>
<% end %>

app/views/admin/products/_products_table.html.erb
<table width="100%">
  <caption>Barang</caption>
  <thead>
  <th>Nama Produk</th>
  <th>Deskripsi</th>
  <th>Harga Beli</th>
  <th>Harga Sewa</th>
  <th>Stok</th>
  <th colspan="5"></th>
</thead>
<% @products.each do |product| %>
  <tr class="<%= cycle('odd', '') %>">
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td class="right"><%= money_format(product.price) %></td>
    <td class="right"><%= money_format(product.rent_price) %></td>
    <td class="right"><%= product.stock %></td>
    <td class="iconed_text"><%= link_to iconed_text('det','Stok'), admin_product_product_stocks_path(product) %> <!-- product_stocks :index --></td>
    <td class="iconed_text"><%= link_to iconed_text('det','Lihat'), [:admin, product] %></td>
    <td class="iconed_text"><%= link_to iconed_text('edit','Ubah'), edit_admin_product_path(product), :rel => 'facebox' %></td>
    <td class="iconed_text"><%= link_to iconed_text('del','Hapus'), [:admin, product], confirm: 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
<tr>
  <td class="center" colspan="10"><%= paginate @products %></td>
</tr>
</table>

app/views/admin/products/_search.html.erb
<div class="panel">
  <div class="header">
    Cari Barang
  </div>

  <%= form_tag admin_products_path, :method => :get, :remote => true do %>
    <%= render :partial => 'search_form' %>
  <% end %>
</div>

app/views/admin/products/_search_form.html.erb
<div class="main-content">
  <div class="form">
<%#= label_tag 'Nama Barang' %>
    <%= text_field_tag :usage_date, @usage_date, :size => '5', :maxlength => '10', :placeholder => "untuk tanggal" %>
      <button id="btn_usage_date">...</button>
      <script type="text/javascript">
        //<![CDATA[
        Calendar.setup({
          inputField : "usage_date",
          trigger : "btn_usage_date",
          onSelect : function() {
            $("#search_products").submit();
            this.hide();
          },
          dateFormat : "%Y-%m-%d"
        });
        //]]>
      </script>

    <%= text_field_tag :name, @product.name, :placeholder => 'nama barang' %>

    <%= select_tag :is_rented, options_for_select({"Barang Sewa" => "true",
        "Barang Non Sewa" => "false"}, :selected => "#{@product.is_rented}") %>

    <%= select_tag :is_package, options_for_select({"Dua-duanya" => "",
        "Paket" => "true",
        "Non Paket" => "false"}, :selected => "#{@product.is_package}") %>

    <%= select_tag :is_dimensional, options_for_select({"Dua-duanya" => "",
        "Tenda" => "true",
        "Non Tenda" => "false"}, :selected => "#{@product.is_dimensional}") %>
      
    <%= hidden_field_tag :order_id, @order.id unless @order.blank? %>
  </div>
</div>

<div class="footer">
  <%= submit_tag 'Cari', :id => 'search_button' %>
</div>

app/views/admin/products/_show.html.erb
<div class="panel">
  <div class="header">
    Detail Barang
  </div>
  <div class="main-content">
    <div class="form">
      <label>Nama Barang</label>
      <div class="show"><%= product.name %></div><br/>

      <label>Deskripsi</label>
      <div class="show"><%= product.description %>&nbsp;</div><br/>

      <% unless product.is_package? %>
        <label>Harga Baru</label>
        <div class="show"><%= product.price %></div><br/>
      <% end %>
        
      <label>Harga Sewa</label>
      <div class="show"><%= product.rent_price %></div><br/>

      <label>Stok</label>
      <div class="show"><%= product.stock %></div><br/>
    </div>
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="panel">
  <div class="header">
    Ubah Barang
  </div>
  <%= render 'form' %>
</div>

app/views/admin/products/index.html.erb
<%= render :partial => 'search' %>
<br/>

<div class="table_list" id="products_table">
  <%= render :partial => 'products_table' %>
</div>
<br/>

<div class="link">
  <%= link_to 'Tambah Barang', new_admin_product_path, :rel => 'facebox' %>
</div>

app/views/admin/products/index.js.erb
$('#products_table').html('<%= escape_javascript(render :partial => "products_table") %>');
$.setAjaxPagination();

app/views/admin/products/new.html.erb
<div class="panel">
  <div class="header">
    Tambah Barang
  </div>
  <%= render 'form' %>
</div>

app/views/admin/products/order.html.erb
<div class="panel">
  <div class="header">&nbsp;</div>

  <%= form_for([:admin, @ordered_product]) do |f| %>
    <div class="main-content">
      <div class="form">
        <%= f.label 'Produk' %>&nbsp;
        <%= f.hidden_field :product_id %><br/>
        <div class="show"><%= @ordered_product.product.name %></div><br/>

        <%= f.label 'Quantity' %>&nbsp;
        <%= f.text_area :qty %><br/>

        <%= f.label 'Deskripsi' %>&nbsp;
        <%= f.text_area :description %><br/>
      </div>
    </div>
  
    <div class="footer">
      <%= f.submit %>
    </div>
  <% end %>

</div>

app/views/admin/products/show.html.erb
<%= render :partial => 'show', :locals => { :product => @product } %>

<br/>

<div class="link">
  <%= link_to 'Ubah', edit_admin_product_path(@product), :rel => "facebox" %>
  <%= link_to 'Kembali', admin_products_path %>
  <%= link_to 'Tambah stok', new_admin_product_product_stock_path(@product), :rel => 'facebox' %>
</div>

<br/>

<% if @product.is_package? %>
  <div class="link">
    <!-- product_packages/new.html.erb -->
    <%= link_to 'Tambah Produk Sebagai Paket', new_admin_product_product_package_path(@product), :rel => "facebox" %>
  </div>

  <br/>

  <%= render :partial => 'admin/product_packages/list', :locals => { :product_packages => @product_packages } %>
<% end %>

app/views/admin/products/xxx_search_form.html.erb
<div class="main-content">
  <div class="form">
<%#= label_tag 'Nama Barang' %>
    <%= text_field_tag :name, @product.name, :placeholder => 'nama barang' %>
    <%= select_tag :is_rented, options_for_select({"Barang Sewa" => "true",
        "Barang Non Sewa" => "false"}, :selected => "#{@product.is_rented}") %>
    <%= select_tag :is_package, options_for_select({"Dua-duanya" => "",
        "Paket" => "true",
        "Non Paket" => "false"}, :selected => "#{@product.is_package}") %>
    <%= select_tag :is_dimensional, options_for_select({"Dua-duanya" => "",
        "Tenda" => "true",
        "Non Tenda" => "false"}, :selected => "#{@product.is_dimensional}") %>
  </div>
</div>

<div class="footer">
  <%= submit_tag 'Cari', :id => 'search_button' %>
</div>

app/views/admin/products/xxx_search_in_order.html.erb
<div class="panel">
  <div class="header">
    Cari Barang
  </div>

  <%= form_tag admin_order_edit_detail_path(@order), :method => :get, :remote => true do %>
    <%= render :partial => 'admin/products/search_form' %>
  <% end %>
</div>